

server:
  port: 8887
spring:
  datasource:
#    url: jdbc:postgresql://localhost:5432/postgres
#    username: postgres
#    password: root
    driver-class-name: org.postgresql.Driver
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
#  jpa:
#    hibernate:
#      ddl-auto: update
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.forum.forum.mapper
  mapper-locations: classpath:mapper/*.xml

jwtSecret: me.zack
jwtExpiration: 86400

#logging.file.path=logs/community.log
#logging.level.com.forum.forum.mapper=debug
#logging.file.max-size=10MB
#logging.file.max-history=100
