server:
  port: 8887
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  flyway:
    url: ${JDBC_DATABASE_URL}
    user: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.forum.forum.mapper
  mapper-locations: classpath:mapper/*.xml

jwtSecret: me.zack
jwtExpiration: 86400
defaultUserAvatartUrl: "https://storage.googleapis.com/spring-forum-1cec4.appspot.com/images/profile1.jfif?GoogleAccessId=firebase-adminsdk-t4is3@spring-forum-1cec4.iam.gserviceaccount.com&Expires=1623528500&Signature=aAsgX9iJ0%2FQvbDSfQRZxZgN1Gbc8uU%2FUZANNbFVyeO8YwUMjDOZxz29IEZeLIUKQW9p8L71qDqvvPzxHnBfVW9pNeGVdsf2SZKi1nMaicPcBlfP4Ymivl07O17eaEOKBBQB4d74ksBOCvHPwf%2BlOMLtmfJUQ0SIomOP8awXRhlZPiH7eHa9jcRuHxHkafSXAFBMsKQjT4U0SKUFU9kANjzY2XRxVb5Bd5x8IESaRGUHShbgsuFq06dRDvZgzdTpTpSb0r7OA62IvEeTBJT5sa0yxJlgbZKsuQG1ynFtdqo5ll%2Bq8tfbWy3Br55hVGwHD9dIzstSEyr7WvLt8qmfNYw%3D%3D"

